#ifndef MACROS_H
#define MACROS_H

#define PIXEL_SCALE 3

#define BLOCK_SIZE 16
#define WALL_WIDTH 8

#define MAZE_WIDTH 13
#define MAZE_HEIGHT 15

#define PLAYER_SPEED 100.f
#define PUSH_SPEED 300.f

#define HUD_SIZE_TOP 72
#define HUD_SIZE_BOTTOM 24

#define WINDOW_WIDTH BLOCK_SIZE * (MAZE_WIDTH + 1) * PIXEL_SCALE
#define WINDOW_HEIGHT BLOCK_SIZE * PIXEL_SCALE * (MAZE_HEIGHT + 1) + HUD_SIZE_BOTTOM + HUD_SIZE_TOP;

#define FONT_PATH "pengo_arcade.ttf"
#define FONT_SIZE 48

#endif // MACROS_H